#######################
# CatBoost Parameters #
#######################

catboost_config:
  class: catboost.CatBoostClassifier
  requires_scaling: False
  data_encoding: "none"

  model_params:
    loss_function: "Logloss"
    eval_metric: "recall"
    auto_class_weights: "Balanced"
    allow_writing_files: False
    verbose: 0

  search_space:
    iterations:
      type: Integer
      low: 500
      high: 3000

    learning_rate:
      type: Real
      low: 0.01
      high: 0.3
      prior: log-uniform

    depth:
      type: Integer
      low: 4
      high: 10

    l2_leaf_reg:
      type: Real
      low: 1e-4
      high: 10.0
      prior: log-uniform

    subsample:
      type: Real
      low: 0.6
      high: 1.0
