########################
# LightGBM Parameters #
########################

lightgbm_config:
  class: lightgbm.LGBMClassifier
  requires_scaling: False
  data_encoding: "label"

  model_params:
    n_jobs: -1
    objective: "binary"
    metric: "binary_logloss"
    boosting_type: "gbdt"
    is_unbalance: True
    verbose: -1

  search_space:
    learning_rate:
      type: Real
      low: 0.005
      high: 0.2
      prior: log-uniform

    max_depth:
      type: Integer
      low: 4
      high: 15

    n_estimators:
      type: Integer
      low: 300
      high: 2000

    num_leaves:
      type: Integer
      low: 10
      high: 100

    subsample:
      type: Real
      low: 0.7
      high: 1.0

    colsample_bytree:
      type: Real
      low: 0.7
      high: 1.0

    reg_alpha:
      type: Real
      low: 0.001
      high: 1.0
      prior: log-uniform

    reg_lambda:
      type: Real
      low: 0.001
      high: 1.0
      prior: log-uniform
