model_registry:
  random_forest:
    name: RandomForestClassifier
    yaml_header: random_forest_config
    train_now: True
    
  xgboost:
    name: XGBoostClassifier
    yaml_header: xgboost_config
    train_now: True
  

