services:
  kedro-pipeline:
    container_name: kedro-pipeline
    build:
      context: .
      dockerfile: dockerfile
    image: higherground189/egt309-team-harish-kanna-kedro-pipeline
    volumes:
      - ./data:/app/data
  visualisation-server:
    container_name: visualisation-server
    build:
      context: visualisation-server/
      dockerfile: dockerfile
    image: higherground189/egt309-team-harish-kanna-kedro-visualisation-server
    ports:
      - "5500:5500"
    volumes:
      - ./data/06_models:/app/saved_models
