model_registry_config:
  random_forest:
    name: RandomForestClassifier
    model_config_key: random_forest_config
    train_now: True
    evaluate_now: True

  xgboost:
    name: XGBoostClassifier
    model_config_key: xgboost_config
    train_now: True
    evaluate_now: True

  lightgbm:
    name: LightGBMClassifier
    model_config_key: lightgbm_config
    train_now: True
    evaluate_now: True

  svm:
    name: SVCClassifier
    model_config_key: svc_config
    train_now: False
    evaluate_now: False

  adaboost:
    name: AdaBoostClassifier
    model_config_key: adaboost_config
    train_now: True
    evaluate_now: True

  catboost:
    name: CatBoostClassifier
    model_config_key: catboost_config
    train_now: True
    evaluate_now: True
