name: Move Notebooks to notebooks/

on:
  push:
    branches: [main]
    paths:
      - "*.ipynb" # run only when .ipynb files are in root
      - "!eda.ipynb"
  pull_request:
    branches: [main]
    paths:
      - "*.ipynb" # run only when .ipynb files are in root
      - "!eda.ipynb"

permissions:
  contents: write

concurrency:
  group: global

jobs:
  move-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Move .ipynb files to notebooks/
        run: mv *.ipynb notebooks/

      - name: Commit & push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          rebase: true
          message: 'chore: Moved notebooks to notebooks/ folder'
