name: Move Notebooks to notebooks/

on:
  push:
    branches: [main]
    paths:
      - "*.ipynb" # run only when .ipynb files are in root

permissions:
  contents: write

jobs:
  move-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Move .ipynb files to notebooks/
        run: mv *.ipynb notebooks/

      - name: Commit & push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: 'chore: Moved notebooks to notebooks/ folder'
