name: Format and Lint .py or .ipynb files

on:
  push:
    branches: [main]
    paths:
      - '**/*.py'
      - 'notebooks/*.ipynb'
  pull_request:
    branches: [main]
    paths:
      - '**/*.py'
      - 'notebooks/*.ipynb'
  workflow_run:
    workflows: ["Move Notebooks to notebooks/", "Copy Notebooks to Main"]
    branches: [main]
    types: [completed]
    
permissions:
  contents: write

concurrency:
  group: global

jobs:
  format-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Lint code with Ruff
        run:  uvx ruff check --fix-only .

      - name: Format code with Ruff
        run:  uvx ruff format .

      - name: Commit & push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          rebase: true
          message: 'chore: Applied Ruff fixes/formatting'



      

      

