name: Format and Lint .py or .ipynb files

on:
  push:
    branches: [main]
    paths:
      - '**/*.py'
      - 'notebook/*.ipynb'
  pull_request:
    branches: [main]
    paths:
      - '**/*.py'
      - 'notebook/*.ipynb'
  workflow_run:
    workflows: ["Move Notebooks to notebooks/"]
    branches: [main]
    types: [completed]
    

permissions:
  contents: write

jobs:
  format-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Lint code with Ruff
        run:  uvx ruff check --fix-only .

      - name: Format code with Ruff
        run:  uvx ruff format .

      - name: Commit & push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: 'chore: Applied Ruff fixes/formatting'



      

      

