name: Format and Lint YAML files

on:
  push:
    branches: [ main ]
    # paths:
    #   - "**/*.yml"
    #   - "**/*.yaml"
  pull_request:
    branches: [ main ]
    # paths:
    #   - "**/*.yml"
    #   - "**/*.yaml"

permissions:
  contents: write

jobs:
  yamlfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.23'
      
      - name: Install Run yamlfmt
        run: go install github.com/google/yamlfmt/cmd/yamlfmt@v0.20.0
      
      - name: Run yamlfmt
        run: yamlfmt -v . --exclude .github/workflows/** --gitignore-excludes

      - name: Commit & push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: 'chore: Applied yamlfmt formatting'